### ISSUE TITLE
Is this abandonware?

### ISSUE THREAD

**Issue by phene** [exoscale/pithos#77]
No active branches and no responses to open PRs or Issues in months.

**Comment by pyr** [comment]
Hi @phene,

The project is definitely not abandonned, it's performing well in production for a number of use-cases. As you might have noticed, the two open PRs are waiting for feedback since one is unmergeable and in the other there are a number of comments that have had no response.

I am sorry the issues went unnoticed, I'll try to make sure they don't in the future.

As for active branches, all small fixes go to master, in the coming months, there are two big ticket items that will be tackled:

- A switch to component to implement modularity
- Signature V4 support

There is also hope of onboarding more maintainers in the project.

**Comment by phene** [comment]
Thanks for the response! Glad to know this project is still active.
